// <auto-generated />
namespace WebApiOdata.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class pessoaecontextoadicionadas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pessoaecontextoadicionadas));
        
        string IMigrationMetadata.Id
        {
            get { return "202011110340091_pessoa e contexto adicionadas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
